CREATE TABLE plt_report(
e_month INT, e_total REAL, pre_acc REAL,
imp_acc REAL, e_total1 REAL, pre_acc1 REAL,
imp_acc1 REAL, o_ops REAL, o_gzw REAL,
o_gzh REAL, o_gzp REAL, o_gze REAL,
o_gzs REAL, o_fon REAL, o_fos REAL,
o_zhq REAL, o_nng REAL, o_zha REAL,
o_hke REAL, s_james REAL, s_austin REAL,
s_ivy REAL, s_louis REAL, s_elaine REAL,
s_colin REAL, s_yaoqi REAL, s_elizabeth REAL,
s_hellen REAL, s_gza REAL, s_gzb REAL,
s_gzc REAL, s_gzg_gda REAL, s_gzd REAL,
s_gzf REAL, s_gwc REAL, s_gwe REAL,
s_gwf REAL, s_gwg REAL, s_gwh REAL,
s_geb REAL, s_gec REAL, s_ged REAL,
s_gee REAL, s_gef REAL, s_gpo REAL,
s_gpb REAL, s_gpc REAL, s_gpd REAL,
s_gpe REAL, s_ghb REAL, s_ghc REAL,
s_ghd REAL, s_ghe REAL, s_fne REAL,
s_fnf REAL, s_fnh REAL, s_fnk REAL,
s_zhq REAL, s_nnb REAL, s_fsa REAL,
s_fsb REAL, s_fsc REAL, s_fsd REAL,
s_hac REAL, s_zhc REAL, s_geo REAL,
s_gen_gwn REAL, s_gwo REAL, s_gwq REAL,
s_gzv_gws REAL, s_gzy REAL, s_fnm REAL,
s_fsy_fnn REAL, s_fsv REAL, s_gpu REAL,
s_ghp REAL, s_gho_gpr REAL, s_ght_gpv_f12_fnp_nnk_zqf_hai_zhl REAL, s_gwt_gzu_get REAL
);