from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String, Float

Base = declarative_base()


class Shippment(Base):
    __tablename__ = 'ecom_test'

    id = Column(Integer, primary_key=True)
    sd_dtm = Column(String(30))
    awb_no = Column(String(20))
    orig_ctry = Column(String(10))
    orig_stn = Column(String(10))
    orig_fclty = Column(String(10))
    cleaned_orig_city_name = Column(String(60))
    sd_route_id = Column(String(10))
    dest_ctry = Column(String(10))
    cleaned_del_zip = Column(String(10))
    cleaned_dest_city_name = Column(String(60))
    shacct_no = Column(String(20))
    billing_acct_no = Column(Integer)
    ship_ref = Column(String(60))
    piece_no = Column(String(10))
    eShipperCompany = Column(String(60))
    eShipperContact = Column(String(60))
    eShipperAddress1 = Column(String(90))
    eShipperAddress2 = Column(String(90))
    eShipperAddress3 = Column(String(90))
    eShipperZip = Column(String(10))
    eshipperCity = Column(String(35))
    eShipperState = Column(String(35))
    eshipperPhone = Column(String(10))
    eshipperFax = Column(String(35))
    esignName = Column(String(35))
    esiteid = Column(String(35))
    eclientVer = Column(String(35))
    eclientApp = Column(String(35))
    cSales_cd = Column(String(10))
    csegment = Column(String(10))
    csale_route = Column(String(10))
    copen_date = Column(String(10))
    cname = Column(String(90))
    cstation = Column(String(10))
    msales_name = Column(String(10))
    mAcctatt = Column(String(10))
    mchannel = Column(String(20))
    marea = Column(String(10))
    mcluster = Column(String(10))
    mroute_name = Column(String(10))
    mghost = Column(String(10))
    meCOM = Column(String(10))
    mopms = Column(String(10))
    cntOfErr = Column(String(10))
    errMemo = Column(String(10))
    message_create_dtm_ecom = Column(String(20))
    Montime = Column(String(10))
    exemptEFR = Column(String(35))
    cleaned_product_code = Column(String(5))
    billing_acct_no_ctry = Column(String(20))
    ezsite_authorizing = Column(String(5))
    extra_charge = Column(String(35))
    PLT = Column(String(5))
    EshipMI = Column(Integer)
    plt_account = Column(Integer)
